---
ap_releases: https://downloads.activestate.com/ActivePython/releases
ap_python2_version: 2.7.13.2715
ap_python2_package_name: "ActivePython-{{ap_python2_version}}-linux-x86_64-glibc-2.12-402695"
ap_python2_package_file_name: "{{ap_python2_package_name}}.tar.gz"
ap_python2_package_download_url: "{{ap_releases}}/{{ap_python2_version}}/{{ap_python2_package_file_name}}"